version: "3.9"
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: ai_arch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: [ "5432:5432" ]
  api:
    build: ../
    ports: [ "8000:8000" ]
    depends_on: [ db ]
